### ISSUE TITLE
Bright orange looks like A leprechauns pot of gold 

### ISSUE THREAD

**Issue by rooyick** [CaltropUwU/TropBot#3]
![15722B89-C7A7-4DC2-A5A1-52863C0599DA](https://user-images.githubusercontent.com/54271960/63261979-cb929980-c252-11e9-9d0c-293a6541bbde.jpeg)
![767F7545-45AD-40AD-9BFB-70EE2341D4B0](https://user-images.githubusercontent.com/54271960/63261980-cb929980-c252-11e9-80eb-80a55e2ff18d.png)
![49B16A64-1FD8-4A68-918F-3F853C90C8FB](https://user-images.githubusercontent.com/54271960/63261982-cb929980-c252-11e9-9a8d-c497f66e6fae.jpeg)

Pls fix or rooyick will have a mental breakdown because he’s really quirky like that

**Comment by CaltropUwU** [comment]
Fixed in v3
