### ISSUE TITLE
CNY not Identified and converted.

### ISSUE THREAD

**Issue by Tsu-ki** [CaltropUwU/TropBot#5]
**Describe the bug**
Chinese yuans aren't converted by $cv nor identified.

**To Reproduce**
$cv <value>cny eur

**Expected behavior**
Expected to convert Chinese Yuan [Renminbi/RMB] to another currency.

**Screenshots**
![OfIFEwv](https://user-images.githubusercontent.com/54984006/66230693-fd699d80-e6e4-11e9-91d1-558dedaec3f6.png)

**Additional context**
N/A

**Comment by Tsu-ki** [comment]
**The issue also seem to happen with rmb**

**Comment by dot-underscore-dot** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #5: CNY not Identified and converted.](https://trello.com/c/CIPMrnlv/1-issue-5-cny-not-identified-and-converted)

**Comment by CaltropUwU** [comment]
Fixed in v3
