### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by ToeMah** [CaltropUwU/TropBot#8]
**UNACCEPTABLE**
The description of the `removewarn` command is missing (literally says "placeholder text")

**HOW**
$help or $help removewarn

**IT JUST WORKS**
Concisely explains the command effect

**SHINY IMAGERY**
![image](https://user-images.githubusercontent.com/53583818/67978383-49433000-fc1a-11e9-951e-7b137464310b.png)
![image](https://user-images.githubusercontent.com/53583818/67978410-552ef200-fc1a-11e9-8be9-14bec414618e.png)

**ILYA**
Both devs are very cute and I hope they'll be happy I'm using the bug report functionality of github uwu

**Comment by dot-underscore-dot** [comment]
<3
